version: '3'
services:
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gym
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web_nw
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.prod
    networks:
      - web_nw
    volumes:
      - static-ui-content:/app/build
  redis:
    image: "redis:5.0.4-stretch"
    ports:
      - "6379"
    networks:
      - web_nw
  check-executor:
    build:
      context: check_executor
      dockerfile: Dockerfile.prod
    networks:
      - web_nw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  check-executor-worker:
    build:
      context: check_executor
      dockerfile: Dockerfile.prod
    entrypoint: celery
    command: -A run.celery worker --loglevel=info
    networks:
      - web_nw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
    depends_on:
        - check-executor
        - db
    networks:
      - web_nw
    volumes:
      - ./courses:/courses
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile.prod
    depends_on:
      - ui
      - api
    ports:
      - "80:80"
    networks:
      - web_nw
    volumes:
      - static-ui-content:/ui
networks:
  web_nw:
    driver: bridge
volumes:
  static-ui-content:
  db_data:
    